#! /usr/bin/env python
# encoding: utf-8

def options(opt):
	# We are using C++
	opt.load('compiler_cxx')

def configure(conf):
	# We are using C++
	conf.load('compiler_cxx')

def build(bld):
	bld.shlib(source='exLibC/src/exLibC.cpp', includes='exLibC/src/include', target='exampleLibC', export_includes='exLibC/src/include/')
	bld.program(source=bld.path.ant_glob('exProgLinkedC/src/*.cpp'), target='exampleProgLinkedC', use='exampleLibC')


